version: "3.8"

services:
  app:
    build:
      context: ./php/presupuesto
    container_name: symfony_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html
    #volumes:
    #  - ./php/presupuesto:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "80:80"  # Apache usará el puerto 80 en el contenedor
    networks:
      - symfony_network

networks:
  symfony_network:
      driver: bridge