    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
vich_uploader:
    db_driver: orm
    mappings:
        referencias:
            uri_prefix: /uploads/referencias
            upload_destination: '%kernel.project_dir%/public/uploads/referencias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
